languageCode = "en"
languageName = "English"
weight = 1

title = "cgutierr-zgz"

[params]
  description = "Carlos Gutiérrez - Software Developer"
  dateFormat = "2 January 2006"
  rtl = false
  isoCode = "en"
  displayName = "EN"

# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Carlos Gutiérrez"
  #image = "img/profile.jpeg"
  headline = "Mobile Developer"
  # bio = "A little bit about you"
  links = [
    { email = "mailto:carlosgutimo.3d@gmail.com" },
    { github = "https://github.com/cgutierr-zgz" },
    { x = "https://x.com/_cgutierr" },
    { linkedin = "https://www.linkedin.com/in/cgutierr" },
  ]
